# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Prince | Configure license.'
  become: yes
  template:
    src: '{{ prince_license_template }}'
    dest: '/usr/local/lib/prince/license/license.dat'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: 'prince_license_template | default(None) != None'