# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Prince | Include OS-specific variables.'
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'prince'
    - 'prince-package'
    - 'prince-configure'
    - 'package'
    - 'configure'

- import_tasks: 'package.yml'
  tags:
    - 'prince'
    - 'prince-package'
    - 'package'

- import_tasks: 'configure.yml'
  tags:
    - 'prince'
    - 'prince-configure'
    - 'configure'