# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Prince | Debian | Install Dependencies.'
  become: yes
  apt:
    name: 'apt-transport-https'
    state: 'present'
  with_items:
    - 'apt-transport-https'
    - 'xz-utils'
  when: 'ansible_os_family == "Debian"'

- name: 'Prince | Debian | Install Prince.'
  become: yes
  apt:
    deb: '{{ prince_url }}'
    state: '{{ prince_state }}'
  when: 'ansible_os_family == "Debian"'

- name: 'Prince | RedHat | Install Prince.'
  become: yes
  yum:
    name: '{{ prince_url }}'
    state: '{{ prince_state }}'
  when: 'ansible_os_family == "RedHat"'
