# This source file is subject to the (Open Source Initiative) BSD license
# that is bundled with this package in the LICENSE file. It is also available
# through the world-wide-web at this URL: http://www.ontic.com.au/license.html
# If you did not receive a copy of the license and are unable to obtain it through
# the world-wide-web, please send an email to license@ontic.com.au immediately.
# Copyright (c) 2010-2016 Ontic. (http://www.ontic.com.au). All rights reserved.

---

- name: 'Prince | Debian | Install HTTPS transport.'
  become: yes
  apt:
    name: 'apt-transport-https'
    state: 'present'
  when: '{{ ansible_os_family == "Debian" }}'

- name: 'Prince | Debian | Install Prince.'
  become: yes
  apt:
    deb: '{{ prince_url }}'
    state: '{{ prince_state }}'
  when: '{{ ansible_os_family == "Debian" }}'

- name: 'Prince | RedHat | Install Prince.'
  become: yes
  yum:
    name: '{{ prince_url }}'
    state: '{{ prince_state }}'
  when: '{{ ansible_os_family == "RedHat" }}'